#!/usr/bin/env bash

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors 
source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

SPACE_CLICK_SCRIPT="yabai -m space --focus \$SID 2>/dev/null" # The script that is run for clicking on space components
ITEM_CORNER_RADIUS=3
ITEM_BACKGROUND_HEIGHT=26
ITEM_PADDING=14

# helper process
# HELPER=git.felix.helper
# killall helper
# cd $HOME/.config/sketchybar/helper && make
# $HOME/.config/sketchybar/helper/helper $HELPER > /dev/null 2>&1 &

# FONT="SF Pro"

# Set up your own custom sketchybar config here
sketchybar --bar height=32 \
		color=$BAR_COLOR \
		margin=0 \
		blur_radius=20 \
		padding_right=23 \
		padding_left=23 \
		notch_width=188


sketchybar --default \
                icon.color=$ICON_COLOR \
	        icon.font.size=16 \
                background.corner_radius=$ITEM_CORNER_RADIUS \
                background.color=$SPACE_DESELECTED \
                background.height=24 \
                icon.padding_left=5 \
                label.padding_right=5 \
                icon.padding_right=5 \
                padding_left=2 \
                padding_right=2

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
# source "$ITEM_DIR/front_app.sh"

# Right
# TIME AND DATE
sketchybar --add item time right \
           --set      time script="$PLUGIN_DIR/time.sh" \
                           update_freq=5 \
                           padding_left=2  \
                           padding_right=8 \
                           icon=$ICON_CLOCK \
           --add item date right \
           --set      date script="$PLUGIN_DIR/date.sh" \
                           update_freq=60  \
                           padding_left=8 \
                           padding_right=2 \
                           icon=$ICON_CALENDAR

# sketchybar --add bracket clock time date
#            --set clock background.color=$TEST_BACKGROUND \
#                                background.border_color=$RED



# sketchybar --add item  volume right                                  \
#            --set       volume script="$PLUGIN_DIR/volume.sh"         \
#                               padding_left=2                         \
#                               padding_right=2                        \
#                               background.border_width=0              \
#                               background.height=24                   \
#            --subscribe volume volume_change

sketchybar --add item  battery right                       \
           --set       battery script="$PLUGIN_DIR/battery.sh"       \
                               update_freq=120                       \
                               padding_left=8                        \
                               padding_right=2                       \
                               background.border_width=0             \
                               background.height=24                  \
           --subscribe battery system_woke power_source_change

source "$ITEM_DIR/volume.sh"
sketchybar --update
