# background #090E13
background #000000
foreground #C5C9C7
selection_background #393B44
selection_foreground #C5C9C7
url_color #72A7BC
cursor #C5C9C7
cursor_text_color #090E13

# Tabs
active_tab_background #090E13
active_tab_foreground #C5C9C7
inactive_tab_background  #090E13
inactive_tab_foreground #A4A7A4


#Regular are kanso mine, brighter are more even
#
# 0 Black
color0 #0d0c0c
# 1 Red
color1 #CD6058
# 2 Green
color2 #7F9F6E 
# 3 Yellow
color3 #CAAC7A
# 4 Blue
color4 #7AADAC
# 5 Magenta
color5 #859FC2
# 6 Cyan
color6 #9F86A2
# 7 White
color7 #C8C093
# 8 Bright Black (Dark Gray)
color8  #A4A7A4
# 9 Bright Red
color9  #F64A54
# 10 Bright Green
color10 #74A461
# 11 Bright Yellow
color11 #CDA972
# 12 Bright Blue
color12 #74B0B0
# 13 Bright Magenta
color13 #8186B7
# 14 Bright Cyan
color14 #9E82A1
# 15 Bright White
color15 #C5C9C7


# extended colors
color16 #C2825D
color17 #C57D5B


# Thanks mitchellh
#--------------------------------------------------------------------
# Theme
#--------------------------------------------------------------------
# Based on https://github.com/sonph/onehalf
# By https://github.com/dbinary
#
# foreground            #dcdfe4
# background            #282c34
# selection_foreground  #000000
# selection_background  #FFFACD
# url_color             #0087BD
#
# # black
# color0   #282c34
# color8   #5d677a
#
# # red
# color1   #e06c75
# color9   #e06c75
#
# # green
# color2   #98c379
# color10  #98c379
#
# # yellow
# color3   #e5c07b
# color11  #e5c07b
#
# # blue
# color4  #61afef
# color12 #61afef
#
# # magenta
# color5   #c678dd
# color13  #c678dd
#
# # cyan
# color6   #56b6c2
# color14  #56b6c2
#
# # white
# color7   #dcdfe4
# color15  #dcdfe4
#
