#!/usr/bin/env sh

#After a restart execute this
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config                                 \
    external_bar                 all:0:0       \
    menubar_opacity              1.0            \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_insertion_point       focused        \
    window_zoom_persist          on             \
    window_shadow                off             \
    window_animation_duration    0.0            \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  4             \
    bottom_padding               4             \
    left_padding                 4             \
    right_padding                4             \
    window_gap                   8             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

yabai -m config --display 1 external_bar all:30:0

# mission-control desktop labels
yabai -m space 1 --label code
yabai -m space 2 --label browser
yabai -m space 3 --label chat
yabai -m space 4 --label zoom
yabai -m space 5 --label mail
yabai -m space 6 --label other
yabai -m space 7 --label notes
yabai -m space 8 --label music
yabai -m space 9 --label external

# window rules
yabai -m rule --add app="^kitty$" space=^code
yabai -m rule --add app="^Brave Browser$" space=^browser
yabai -m rule --add app="^Slack$" space=^chat
yabai -m rule --add app="^Zoom$" space=^zoom
yabai -m rule --add app="^Mail$" space=^mail

yabai -m rule --add app="^ZenNotes$" space=^notes

yabai -m rule --add app="^Claude$" space=^other
yabai -m rule --add app="^DBeaver$" space=^other
yabai -m rule --add app="^Preview$" space=^other
yabai -m rule --add app="^Finder$" space=^other
# yabai -m rule --add app="^Obsidian$" space=^other
yabai -m rule --add app="^Notion$" space=^other
yabai -m rule --add app="^Strongbox$" space=^other
yabai -m rule --add app="^Discord$" space=^other
yabai -m rule --add app="^Stremio$" space=^other

yabai -m rule --add app="^Spotify$" space=^music

# specific space settings
yabai -m config --space chat layout stack
yabai -m config --space notes layout stack
yabai -m config --space other layout stack
yabai -m config --space music layout stack
yabai -m config --space external layout stack


# Ignore apps
yabai -m rule --add app="^(Messages|System Settings|Calculator|App Store|Steam|Alfred|Activity Monitor|IINA|GIMP)" manage=off

# focus window after active space changes
yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# trigger sketchybar events for space icon updates
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_moved action="sketchybar --trigger windows_on_spaces"
borders style=square active_color=0xffFFFFFF inactive_color=0xff000000 width=5.0 &

