#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config                                 \
    external_bar                 all:0:0       \
    menubar_opacity              1.0            \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_insertion_point       focused        \
    window_zoom_persist          on             \
    window_shadow                off             \
    window_animation_duration    0.0            \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  8             \
    bottom_padding               4             \
    left_padding                 4             \
    right_padding                4             \
    window_gap                   8             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

yabai -m config --display 1 external_bar all:30:0

# mission-control desktop labels
yabai -m space 1 --label browser
yabai -m space 2 --label code
yabai -m space 3 --label other
yabai -m space 4 --label chat
yabai -m space 5 --label notes
yabai -m space 7 --label music
yabai -m space 8 --label external

# window rules
yabai -m rule --add app="^Zen$" space=^browser
yabai -m rule --add app="^Ghostty$" space=^code
yabai -m rule --add app="^Microsoft Teams$" space=^chat
yabai -m rule --add app="^Obsidian$" space=^notes
yabai -m rule --add app="^Postman$" space=^other
yabai -m rule --add app="^DBeaver$" space=^other
yabai -m rule --add app="^Preview$" space=^other
yabai -m rule --add app="^Finder$" space=^other
yabai -m rule --add app="^Microsoft Outlook$" space=^other
yabai -m rule --add app="^Notion$" space=^other
yabai -m rule --add app="^Spotify$" space=^music

# specific space settings
# yabai -m config --space chat layout stack
# yabai -m config --space other layout stack
# yabai -m config --space notes layout stack
# yabai -m config --space music layout stack


# Ignore apps
yabai -m rule --add app="^(Messages|System Settings|Calculator|App Store|Steam|Alfred|Activity Monitor|Strongbox|IINA)" manage=off

# focus window after active space changes
yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

borders style=round active_color=0xffe1e3e4 inactive_color=0xff494d64 width=4.0 &
# adjust_spaces() {
#   local desired_spaces=("$@")
#   local display=1
#   for desired_space in "${desired_spaces[@]}"; do
#     local actual_space=$(yabai -m query --spaces | jq 'map(select(.display == '$display')) | length')
#     yabai -m display --focus $display
#     while (( actual_space != desired_space )); do
#       if (( actual_space < desired_space )); then
#         yabai -m space --create
#         ((actual_space++))
#       else
#         local last_space_index=$(yabai -m query --spaces | jq '.[].index | select(. == '$spaces_on_display')')
#         yabai -m space --focus $last_space_index
#         yabai -m space --destroy
#         ((actual_space--))
#       fi
#     done
#     ((display++))
#   done
# }

# setup_space() {
#   local idx="$1"
#   local name="$2"
#   yabai -m space "$idx" --label "$name"
# }

# Spaces adjustment
# num_displays=$(yabai -m query --displays | jq 'length')
# if [[ "$num_displays" -eq 3 ]]; then
#     adjust_spaces 3 3 4
# elif [[ "$num_displays" -eq 2 ]]; then
#     adjust_spaces 5 5
# elif [[ "$num_displays" -eq 1 ]]; then
#     adjust_spaces 5
# fi
# mouse settings
# yabai -m config mouse_follows_focus on
