#!/usr/bin/env sh
# open_and_move() {
# 	alt - $1 : open -a "$2" && yabai -m window --focus "$(yabai -m query --windows --app \"$2\" | jq '.[0].id')"
# }
#App shortcuts
# open_and_move t "iTerm"
# open_and_move b "Brave Browser"
# open_and_move c "Microsoft Teams"
# open_and_move n "Notion"
# open_and_move m "Microsoft Outlook"
# open_and_move p "Postman"
# open_and_move s "Spotify"

# alt - t : open -a "iTerm" && yabai -m space --focus  $(yabai -m query --windows | jq 'map(select(.app = "iTerm"))[0].space') && yabai -m window --focus "$(yabai -m query --windows | jq 'map(select(.app = "iTerm"))[0].id')"


# switch_yabai_layout() {
#     current_layout=$(yabai -m query --spaces --space | jq -r '.type')
#
#     if [ "$current_layout" == "bsp" ]; then
#         yabai -m space --layout stack
#     elif [ "$current_layout" == "stack" ]; then
#         yabai -m space --layout float
#     else
#         yabai -m space --layout bsp
#     fi
# }
# cmd - "tab" : echo 'Get used to it'

lalt - t : open -a "Ghostty"
lalt - b : open -a "Brave Browser"
lalt - c : open -a "Microsoft Teams"
lalt - n : open -a "Notion"
lalt - m : open -a "Microsoft Outlook"
lalt - p : open -a "Postman"
lalt - s : open -a "Spotify"
lalt - v : switch_yabai_layout 

# Window management
lalt - h : yabai -m window --focus west
lalt - j : yabai -m window --focus south
lalt - k : yabai -m window --focus north
lalt - l : yabai -m window --focus east

# Move between spaces
lalt - 1 : yabai -m space --focus  1 
lalt - 2 : yabai -m space --focus  2
lalt - 3 : yabai -m space --focus  3
lalt - 4 : yabai -m space --focus  4
lalt - 5 : yabai -m space --focus  5
lalt - 6 : yabai -m space --focus  6 
lalt - 7 : yabai -m space --focus  7
lalt - 8 : yabai -m space --focus  8
lalt - 9 : yabai -m space --focus  9
lalt - 0 : yabai -m space --focus  10

# send window to desktop and follow focus
shift + alt - 1 : yabai -m window --space  1; yabai -m space --focus 1
shift + alt - 2 : yabai -m window --space  2; yabai -m space --focus 2
shift + alt - 3 : yabai -m window --space  3; yabai -m space --focus 3
shift + alt - 4 : yabai -m window --space  4; yabai -m space --focus 4
shift + alt - 5 : yabai -m window --space  5; yabai -m space --focus 5
shift + alt - 6 : yabai -m window --space  6; yabai -m space --focus 6
shift + alt - 7 : yabai -m window --space  7; yabai -m space --focus 7
shift + alt - 8 : yabai -m window --space  8; yabai -m space --focus 8
shift + alt - 9 : yabai -m window --space  9; yabai -m space --focus 9
shift + alt - 0 : yabai -m window --space  10; yabai -m space --focus 10


# toggle window zoom
# alt - d : yabai -m window --toggle zoom-parent
alt - f : yabai -m window --toggle zoom-fullscreen

# toggle window split type
alt - e : yabai -m window --toggle split
