#!/bin/bash

# Apps
alt - f : open_terminal "kitty" 0
alt - d : open_terminal "kitty" 1
alt - g : open_and_move "Brave Browser"
alt - t : open_and_move "Slack"
alt - z : open_and_move "Zoom"
alt - c : open_and_move "Claude"
alt - m : open_and_move "Mail"
alt - n : open_and_move "ZenNotes"

# Move between spaces
# alt - 1 : yabai -m space --focus  1
# alt - 2 : yabai -m space --focus  2
# alt - 3 : yabai -m space --focus  3
# alt - 4 : yabai -m space --focus  4
# alt - 5 : yabai -m space --focus  5
# alt - 6 : yabai -m space --focus  6
# alt - 7 : yabai -m space --focus  7
# alt - 8 : yabai -m space --focus  8
# alt - 9 : yabai -m space --focus  9
# alt - 0 : yabai -m space --focus  10

# Send to spaces
alt - 1 : yabai -m window --space  1; yabai -m space --focus 1;  
alt - 2 : yabai -m window --space  2; yabai -m space --focus 2;
alt - 3 : yabai -m window --space  3; yabai -m space --focus 3;
alt - 4 : yabai -m window --space  4; yabai -m space --focus 4;
alt - 5 : yabai -m window --space  5; yabai -m space --focus 5;
alt - 6 : yabai -m window --space  6; yabai -m space --focus 6;
alt - 7 : yabai -m window --space  7; yabai -m space --focus 7;
alt - 8 : yabai -m window --space  8; yabai -m space --focus 8;
alt - 9 : yabai -m window --space  9; yabai -m space --focus 9;
alt - 0 : yabai -m window --space  10; yabai -m space --focus 10;


# External/internal monitor switch
alt - e : yabai -m window --space 8; yabai -m space --focus 8 
alt - i : hook_back

#Navigation
alt - a : yabai -m window --focus recent
alt - j : focus_next
alt - k : focus_prev

# Layout
alt - r : yabai -m space --rotate 270
alt - v : switch_yabai_layout
alt - h : yabai -m window --ratio rel:-0.05
alt - l : yabai -m window --ratio rel:0.05

# Disable cmd tab 
cmd - 0x30 : echo 'Get used to!!'

