#!/usr/bin/env sh

yabai -m config layout bsp
yabai -m config window_placement second_child

# padding
yabai -m config top_padding 5 \
yabai -m config bottom_padding 5 \
yabai -m config left_padding 5
yabai -m config right_padding 5
yabai -m config window_gap 5

# mouse settings
yabai -m config mouse_follows_focus on

# Ignore apps
yabai -m rule --add app="^System Settings" manage=off

# mission-control desktop labels
yabai -m space 1 --label code
yabai -m space 2 --label web
yabai -m space 3 --label notes
yabai -m space 4 --label mail
yabai -m space 5 --label other
# yabai -m config window_shadow float
# yabai -m config window_opacity on
# yabai -m config window_opacity_duration 0.2
# yabai -m config window_opacity_focused 1
# yabai -m config window_opacity_normal 0.9

